# Day 38 --> Intro to Data analytical modules --> Numpy, Pandas, Matplotlib

In [9]:
import numpy as np

In [10]:
#creating 1d array
data = [12,23,34]
a= np.array(data)
a

array([12, 23, 34])

In [11]:
print(type(a))
print(a.ndim)
print(len(a))
print(a.size)
print(a.shape)

<class 'numpy.ndarray'>
1
3
3
(3,)


In [12]:
#creating a 2d array
data2 = np.array([[1,2,3],[4,5,6]])
data2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
print(data2.shape)
print(data2.ndim)#rows --> axis0, columns --> axis1
print(data2.size)
print(data2.itemsize)

(2, 3)
2
6
8


In [14]:
import time
#let us create two lists with around 1000000 elements
l1 = list(range(1000000))
l2 = list(range(1000000))
start = time.time()
l3 = [x+y for x,y in zip(l1,l2)]
end = time.time()
print(f"Execution time for lissts is {(end - start)*1000} milliseconds")

Execution time for lissts is 471.59600257873535 milliseconds


In [15]:
#create elements in numpy arrays usse --> arange()
A1 = np.arange(1000000)
A2 = np.arange(1000000)
start = time.time()
A3 = A1 + A2
end = time.time()
print(f'execution time for numpy arrays is {(end - start) * 1000} milliseconds')

execution time for numpy arrays is 11.045455932617188 milliseconds


#Numpy arrays exhibit atleast 50X times faster than list

In [ ]:
a = np.arange(10).reshape(2,5)
a
b = np.arange(10).reshape(5,2)
b
c = np.arange(10).reshape(-1,2)
c
d = np.arange(10).reshape(2,-1)
d

ValueError: cannot reshape array of size 10 into shape (4,newaxis)

In [41]:
e = np.arange(24).reshape(-1,4)
e
f = np.arange(24).reshape(3,8)
f

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [45]:
print(f+2)
print(f-2)
print(f*2)
print(f/2)
a = np.array([[1,2],[3,4]])
b = np.array([[3,4],[1,2]])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
#statistical methods
print(np.mean(e))
print(np.median(e))
print(np.std(e))
print(np.min(e))
print(np.max(e))
print(np.minimum(a,b))

[[ 2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25]]
[[-2 -1  0  1  2  3  4  5]
 [ 6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21]]
[[ 0  2  4  6  8 10 12 14]
 [16 18 20 22 24 26 28 30]
 [32 34 36 38 40 42 44 46]]
[[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5  6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5 10.  10.5 11.  11.5]]
[[4 6]
 [4 6]]
[[-2 -2]
 [ 2  2]]
[[3 8]
 [3 8]]
11.5
11.5
6.922186552431729
0
23
[[1 2]
 [1 2]]


In [60]:
data = np.array([[1,4,5],[5,6,-9],[2,3,-1]])
print(data)
print(data[0])
print(data[0][1])
print(data[0:,0])
print(data[0:2,1:3]) #, to change axis

[[ 1  4  5]
 [ 5  6 -9]
 [ 2  3 -1]]
[1 4 5]
4
[1 5 2]
[[ 4  5]
 [ 6 -9]]


In [71]:
a = np.linspace(1,10,23,endpoint = True,retstep=True)
a

(array([ 1.        ,  1.40909091,  1.81818182,  2.22727273,  2.63636364,
         3.04545455,  3.45454545,  3.86363636,  4.27272727,  4.68181818,
         5.09090909,  5.5       ,  5.90909091,  6.31818182,  6.72727273,
         7.13636364,  7.54545455,  7.95454545,  8.36363636,  8.77272727,
         9.18181818,  9.59090909, 10.        ]),
 np.float64(0.4090909090909091))

In [74]:
a = np.array([1,3,4,9,-1,2,3])
print(np.sort(a))
print(np.unique(a))
print(np.argmin(a))
print(a > 5)
print(a[a > 5])

[-1  1  2  3  3  4  9]
[-1  1  2  3  4  9]
4
[False False False  True False False False]
[9]


In [73]:
print(np.zeros(3))
print(np.ones((1,4)))
print(np.eye(2))

[0. 0. 0.]
[[1. 1. 1. 1.]]
[[1. 0.]
 [0. 1.]]
