Day-40

In [4]:
import numpy as np

# Array Creation
data = [35,25,35]
a  = np.array(data)
# a  = np.array([1,5,3])
print(a)
a

print(a.ndim)  # return thr dimension of array
print(type(a))
print(len(a))
print(a.size) # return no.of elements in array
print(a.shape)

# 2d array
b = np.array([[1,2,3],[4,5,6]])
print(b)
b

[35 25 35]
1
<class 'numpy.ndarray'>
3
3
(3,)
[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
print(b.ndim)  # return thr dimension of array
print(type(b))
print(len(b))
print(b.size) # return no.of elements in array
print(b.shape) # rows --> axis:0 and col-> axis:1
print(b.itemsize)

2
<class 'numpy.ndarray'>
2
6
(2, 3)
8


In [6]:
# Numpy arr vs list (Faster computation)

# let us creat list of 2

l1 = list(range(10))
l2 = list(range(10))

print(l1+l2) # merging 


# time module for time calcualtion
import time 
start = time.time()
l3 = [x+y for x,y in zip(l1,l2)]
print(l3)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [7]:
l3 = list(range(1000000))
l4 = list(range(1000000))


start = time.time()
l4 = [x+y for x,y in zip(l3,l4)]
end = time.time()

print(f"Excution Time for List is {(end-start)*1000} milliseconds")

Excution Time for List is 216.42565727233887 milliseconds


In [8]:
# creating ele in numpy arr --> arrange()

A1 = np.arange(1000000)
A2 = np.arange(1000000)
start = time.time()
A3 = A1+A2
end = time.time()
print(f"Excution Time for List is {(end-start)*1000} milliseconds")

Excution Time for List is 5.860328674316406 milliseconds


In [10]:
# reshape ()

a = np.arange(10).reshape(2,5)
print(a)
b = np.arange(10).reshape(5,2)
print(b)
c = np.arange(10).reshape(5,2)
print(c)
d = np.arange(10).reshape(2,-1)
print(d)

e = np.arange(24).reshape(-1,4)
print(e)

f = np.arange(24).reshape(3,8)
print(f)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [11]:
print(f+2)
print(f-2)
print(f*2)
print(f/2)

[[ 2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25]]
[[-2 -1  0  1  2  3  4  5]
 [ 6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21]]
[[ 0  2  4  6  8 10 12 14]
 [16 18 20 22 24 26 28 30]
 [32 34 36 38 40 42 44 46]]
[[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5  6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5 10.  10.5 11.  11.5]]


In [12]:
a = np.array([[1,2],[3,4]])
b = np.array([[3,4],[1,2]])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
# statucal method 
print(np.mean(e))
print(np.median(e))
print(np.std(e))
print(np.min(e))
print(np.max(e))

print(np.minimum(a,b))

[[4 6]
 [4 6]]
[[-2 -2]
 [ 2  2]]
[[3 8]
 [3 8]]
11.5
11.5
6.922186552431729
0
23
[[1 2]
 [1 2]]


In [13]:
# indexing ansd Silcing on arrays

data = np.array([[1,4,5],[5,6,-9],[2,3,-1]])
#print(data)
print(data[0][1])
#print(data[0])

print(data[1:,1:])
print(data[0:2,2])

4
[[ 6 -9]
 [ 3 -1]]
[ 5 -9]


In [15]:
# range of numbers --> arrange,linespace

a = np.linspace(1,10)
a
a = np.linspace(1,10,4)
a


array([ 1.,  4.,  7., 10.])